---
# tasks file for tailscale
- name: Import tasks to setup repository.
  ansible.builtin.include_tasks: "repo_{{ ansible_facts['distribution'] }}.yml"

- name: Print distro
  ansible.builtin.debug:
    var: ansible_facts['distribution']

- name: Ensure tailscale is installed.
  ansible.builtin.dnf:
    name: tailscale
    state: present
  become: true

- name: Ensure tailscaled service is started.
  ansible.builtin.service:
    name: tailscaled.service
    state: started
    enabled: true
  become: true

- name: Ensure machine is connected to tailscale network.
  block:
    - name: Check if machine already has an IP assigned.
      ansible.builtin.command:
        cmd: "tailscale ip"
      changed_when: false
  rescue:
    - name: Connect machine to tailscale network
      ansible.builtin.command:
        cmd: "tailscale up --auth-key {{ auth_key }}"
      become: true
      changed_when: true
