---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: instance
    box: generic/rocky9
    memory: 256
    cpus: 1
provisioner:
  name: ansible
verifier:
  name: ansible
